### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mapellil** [dh-electronics/meta-av96#5]
Hello, trying to build https://github.com/dh-electronics/meta-av96/tree/master/meta-av96.thud after having followed succesfully the indicated steps,  bitbake throw the below error seems related to patching process from quilt, any suggestion? thanks, regards

bitbake av96-weston 
NOTE: Started PRServer with DBfile: /mnt/storage/MP1/Distro_kit_avenger/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxweston-stm32mp1-av96/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 33305, PID: 24465
Parsing recipes: 100% |#########################################################################################################| Time: 0:01:44
Parsing of 2549 .bb files complete (0 cached, 2549 parsed). 3596 targets, 85 skipped, 49 masked, 0 errors.
WARNING: No bb files matched BBFILE_PATTERN_security '^/mnt/storage/MP1/Distro_kit_avenger/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-security/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "arm-openstlinux_weston-linux-gnueabi"
MACHINE              = "stm32mp1-av96"
DISTRO               = "openstlinux-weston"
DISTRO_VERSION       = "2.6-snapshot-20200528"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU           = "hard"
DISTRO_CODENAME      = "thud"
ACCEPT_EULA_stm32mp1-av96 = "1"
GCCVERSION           = "8.%"
PREFERRED_PROVIDER_virtual/kernel = "linux-stm32mp"
meta-st-stm32mp-addons = "HEAD:db898de3834a8a2a889a6b43993b8faf22de798c"
meta-python          
meta-oe              
meta-oe              
meta-gnome           
meta-xfce            
meta-initramfs       
meta-multimedia      
meta-networking      
meta-webserver       
meta-filesystems     
meta-perl            
meta-python          = "HEAD:9b3b907f30b0d5b92d58c7e68289184fda733d3e"
meta-st-stm32mp      = "HEAD:d8cbac759e1275b1a27d4ba38b64a0d83d0e8c9f"
meta-qt5             = "HEAD:1520d5b2b2beec5e1c3209d3178219e93ef08bca"
meta-security        
meta-tpm             = "HEAD:51a4c6b5179d087f647cf0c458edb8ab107826ef"
meta-perl            
meta-filesystems     = "HEAD:9b3b907f30b0d5b92d58c7e68289184fda733d3e"
meta-st-openstlinux  = "HEAD:ee276cb390d7dd1175d386ba2bfd384c1b206808"
meta                 = "HEAD:d3d3f443039b03f1200a14bfe99f985592632018"
meta-av96            = "thud:5309a6ebddd65cbcf606fe9a881cf095957975b1"

Initialising tasks: 100% |######################################################################################################| Time: 0:00:15
Sstate summary: Wanted 3013 Found 2996 Missed 17 Current 0 (99% match, 0% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: u-boot-stm32mp-2018.11-r0 do_patch: Command Error: 'quilt --quiltrc /mnt/storage/MP1/Distro_kit_avenger/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxweston-stm32mp1-av96/tmp-glibc/work/stm32mp1_av96-openstlinux_weston-linux-gnueabi/u-boot-stm32mp/2018.11-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0003-av96-drivers.patch
patching file arch/arm/lib/relocate.S
patching file arch/arm/mach-stm32mp/cpu.c
Hunk #3 succeeded at 456 (offset -21 lines).
Hunk #4 succeeded at 483 (offset -21 lines).
Hunk #5 succeeded at 498 (offset -21 lines).
Hunk #6 succeeded at 616 (offset -21 lines).
patching file board/st/stm32mp1/stm32mp1.c
Hunk #2 succeeded at 662 (offset -6 lines).
Hunk #3 succeeded at 739 (offset -6 lines).
Hunk #4 succeeded at 777 (offset -6 lines).
patching file common/board_f.c
patching file common/board_r.c
patching file configs/stm32mp15_basic_defconfig
patching file configs/stm32mp15_trusted_defconfig
patching file drivers/net/dwc_eth_qos.c
Hunk #1 FAILED at 705.
Hunk #2 FAILED at 731.
Hunk #3 succeeded at 1011 (offset -29 lines).
Hunk #4 succeeded at 1044 (offset -29 lines).
Hunk #5 succeeded at 1582 (offset -29 lines).
Hunk #6 FAILED at 1686.
Hunk #7 succeeded at 1750 (offset -45 lines).
3 out of 7 hunks FAILED -- rejects in file drivers/net/dwc_eth_qos.c
patching file drivers/net/phy/micrel_ksz90x1.c
patching file drivers/net/phy/phy.c
patching file include/configs/stm32mp1.h
patching file Makefile
Patch 0003-av96-drivers.patch does not apply (enforce with -f)
ERROR: u-boot-stm32mp-2018.11-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /mnt/storage/MP1/Distro_kit_avenger/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxweston-stm32mp1-av96/tmp-glibc/work/stm32mp1_av96-openstlinux_weston-linux-gnueabi/u-boot-stm32mp/2018.11-r0/temp/log.do_patch.9774
ERROR: Task (/mnt/storage/MP1/Distro_kit_avenger/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-st/meta-st-stm32mp/recipes-bsp/u-boot/u-boot-stm32mp_2018.11.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 8126 tasks of which 6565 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory

Summary: 1 task failed:
  /mnt/storage/MP1/Distro_kit_avenger/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-st/meta-st-stm32mp/recipes-bsp/u-boot/u-boot-stm32mp_2018.11.bb:do_patch
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by davidroid** [comment]
Hello,
I confirm I get exactly the same bad result when following the "https://github.com/dh-electronics/meta-av96/blob/master/meta-av96.thud/readme.txt" readme file, pointed by chapter 1.3.1 of the "DOC_Getting-Started-588-200_R02_2019-10-08.pdf" guide.

In particular, I started from the "STM32MP1_Distribution_Package" V.1.1.0, I cloned the "https://github.com/dh-electronics/meta-av96/tree/master/meta-av96.thud" repository, and followed all the instructions reported by the readme file, i.e.:
        $ cp .../meta-av96.thud/meta-av96 layers/ -R
        $ pushd .
        $ cd layers
        $ patch -p0 < .../meta-av96.thud/meta-st.patch
        $ git clone git://git.yoctoproject.org/meta-security
        $ cd meta-security/
        $ git checkout 51a4c6b5179d087f647cf0c458edb8ab107826ef
        $ cd ../meta-st/meta-st-stm32mp-addons/conf/eula/
        $ ln -s ST_EULA_SLA stm32mp1-av96
        $ popd
        $ DISTRO=openstlinux-weston MACHINE=stm32mp1-av96 source layers/meta-st/scripts/envsetup.sh
        $ bitbake-layers add-layer ../layers/meta-av96/

At the end, when building with "bitbake av96-weston", it gets stuck with the errors reported above by @mapellil .

ISN'T THIS MAYBE THE WRONG PROCEDURE? PLEASE CHECK AND PROVIDE A SOLUTION.

Thank you and regards,
Davide

**Comment by mschmoeller** [comment]
Hello,

the master branch was moved to the default branch "thud".

Please use the instructions here:
https://github.com/dh-electronics/manifest-av96

It seems like the Getting-Started Document is refered to the wrong branch. I'm going to investigate that.

Thank you and best regards,
Martina

**Comment by mapellil** [comment]
Dear Martina,
thank you for your answer, i'm afraid the new branch still does not work. I followed all the instructions indicated here https://github.com/dh-electronics/meta-av96/tree/thud and after MANY MANY MANY try, also on other branches,  wasting the whole week i'm getting tired. Did you try personally to compile from the suggested branch?
Moreover i can confirm: it don't need to much investigations, the GettinStarted guide indicates the wrong branch and the wiki page is not updated.
Thank you in advance for providing a working branch, simply to reproduce the pre-flashed image


________________________________

**Comment by mschmoeller** [comment]
Hi,
did you follow the instructions from the manifest repository, I posted, or from the meta-layer read-me?
Please follow the instruction from the manifest.
https://github.com/dh-electronics/manifest-av96
Also mentioned in the "Avenger96 588-200 Getting-Started R03" Document, provided by our wiki.

The manifest provides all needed meta-layers with specified revisions. 
I checked it personally this morning and it works for me without any build errors.

Best regards,
Martina

**Comment by mapellil** [comment]
Hello, the issue i meet was in the .raw image creation, meaning:
the command
 ./scripts/create_sdcard_from_flashlayout.sh flashlayout_av96-weston/FlashLayout_sdcard_stm32mp157a-av96-trusted.tsv
on my machine required sudo privilege otherwise the sgdisk failed creating an empty .raw img
Additionally, instead of the dd command in the readme i've used the dd suggested by the execution of the above script, so:
sudo dd if=flashlayout_av96-weston_FlashLayout_sdcard_stm32mp157a-av96-trusted.raw bs=8M of=/dev/sdX conv=fdatasync status=progress
So the issue can be considered closed, thanks
